<?php

namespace App\Tests;

use App\Entity\Product;
use App\Tests\Factory\ProductFactory;
use JetBrains\PhpStorm\NoReturn;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Zenstruck\Browser\Test\HasBrowser;
use Zenstruck\Foundry\Test\Factories;
use Zenstruck\Foundry\Test\ResetDatabase;

class ProductControllerTest extends WebTestCase
{
//    use HasBrowser;
    use Factories;
//    use ResetDatabase;



    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $endpoint
     * @param string $method
     * @return void
     * @dataProvider apiEndpoint
     */
    public function testCanNotAccessEndpointsWithoutAuthToken(string $endpoint, string $method): void
    {
        $client = static::createClient();
        $client->request($method, $endpoint);

        $actualResponse = json_decode(
            $client->getResponse()->getContent(),
            true
        );

        $this->assertEquals(401, $client->getResponse()->getStatusCode());
        $this->assertArrayHasKey('code', $actualResponse);
        $this->assertArrayHasKey('message', $actualResponse);

        $this->assertEquals(401, $actualResponse['code']);
        $this->assertEquals('JWT Token not found', $actualResponse['message']);
    }

    #[NoReturn] public function testAddProduct(): void
    {
        $client = $this->createAuthenticatedClient();
        $input = [
            'name' => 'Test',
            'price' => 4000,
            'description' => 'This is a test',
        ];

        $client->request(
            'POST',
            '/api/products',
            [],
            [],
            ['CONTENT_TYPE' => 'application/json'],
            json_encode($input)
        );

        $actualResponse = json_decode(
            $client->getResponse()->getContent(),
            true
        );

        $this->assertArrayHasKey('data', $actualResponse);
        $this->assertArrayHasKey('message', $actualResponse);
        $this->assertEquals('Product created successfully', $actualResponse['message']);

        $this->assertArrayHasKey('id', $actualResponse['data']);
        $this->assertEquals($input['name'], $actualResponse['data']['name']);
        $this->assertEquals($input['price'], $actualResponse['data']['price']);
        $this->assertEquals($input['description'], $actualResponse['data']['description']);
    }

    /**
     * @param $key
     * @param $input
     * @param $validationMessage
     * @return void
     * @dataProvider getFieldAndValidationMessage
     */
    public function testCannotAddProductWithNameOrPrice($key, $input, $validationMessage): void
    {
        $client = $this->createAuthenticatedClient();

        $client->request(
            'POST',
            '/api/products',
            [],
            [],
            ['CONTENT_TYPE' => 'application/json'],
            json_encode($input)
        );

        $this->assertResponseStatusCodeSame(400);
        $actualResponse = json_decode(
            $client->getResponse()->getContent(),
            true
        );

        $this->assertArrayHasKey('errors', $actualResponse);
        $this->assertArrayHasKey('message', $actualResponse);
        $this->assertEquals('Validation failed', $actualResponse['message']);

        foreach ($actualResponse['errors'] as $error) {
            $this->assertEquals($key, $error['property']);
            $this->assertEquals($validationMessage, $error['message']);
        }
    }

    public function testFetchProducts()
    {
        $product = ProductFactory::createMany(5);
//        dd($product);
        $client = $this->createAuthenticatedClient();
        $client->request('GET', '/api/products');

        $this->assertResponseIsSuccessful();

       $this->assertJson();
    }

    public function getFieldAndValidationMessage(): array
    {
        return [
            [
                'key' => 'name',
                [
                    'price' => 4000,
                    'description' => 'This is a test',
                ],
                'Name field is required'
            ],
            [
                'key' => 'price',
                [
                    'name' => 'Test',
                    'description' => 'This is a test',
                ],
                'Price field is required'
            ],
            [
                'key' => 'price',
                [
                    'name' => 'This is a test',
                    'price' => null,
                    'description' => 'This is a test',
                ],
                'Price field is required'
            ],
            [
                'key' => 'name',
                [
                    'price' => 4000,
                    'name' => null,
                    'description' => 'This is a test',
                ],
                'Name field is required'
            ],
        ];
    }

    public function apiEndpoint(): array
    {
        return [
            ['api/products', 'GET'],
            ['api/products', 'POST'],
            ['api/products/1', 'GET'],
            ['api/products/1', 'PUT'],
            ['api/products/1', 'DELETE'],
        ];
    }

    /**
     *
     * @return KernelBrowser
     */
    private function createAuthenticatedClient(): KernelBrowser
    {
        $username = 'hagioswilson@gmail.com';
        $password = 'password';

        $client = static::createClient();
        $client->request(
            'POST',
            '/api/login_check',
            [],
            [],
            ['CONTENT_TYPE' => 'application/json'],
            json_encode([
                'email' => $username,
                'password' => $password,
            ])
        );

        $data = json_decode($client->getResponse()->getContent(), true);
        $client->setServerParameter('HTTP_Authorization', sprintf('Bearer %s', $data['token']));

        return $client;
    }
}
